# Generated by Django 4.2.6 on 2023-10-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='votes',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='like_count',
            field=models.CharField(max_length=200),
        ),
    ]
