# Generated by Django 4.2.6 on 2023-11-13 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_studyspot_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
