# Generated by Django 4.2.5 on 2023-11-14 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_alter_studyspot_latitude_alter_studyspot_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=1000)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_reply', models.BooleanField(default=False)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comment')),
                ('poster', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('replies', models.ManyToManyField(blank=True, null=True, to='users.comment')),
            ],
        ),
        migrations.RemoveField(
            model_name='likes',
            name='spot',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='studyspot',
            name='like_count',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_spots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='user_posted',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.AddField(
            model_name='comment',
            name='study_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studyspot'),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studyspot',
            name='comments',
            field=models.ManyToManyField(to='users.comment'),
        ),
    ]
