# Generated by Django 4.2.5 on 2023-11-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_comment_remove_likes_spot_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(blank=True, to='users.comment'),
        ),
    ]
