# Generated by Django 4.2.6 on 2023-11-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_comment_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='comments',
        ),
    ]
