# Generated by Django 4.2.6 on 2023-11-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_studyspot_user_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, default='0', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, default='0', max_digits=10, null=True),
        ),
    ]
