# Generated by Django 4.2.6 on 2023-11-15 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_comment_parent_comment_remove_comment_replies_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='study_spot',
            new_name='study_spot_parent',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='comments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.comment'),
        ),
    ]
