# Generated by Django 4.2.6 on 2023-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_studyspot_latitude_alter_studyspot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, default='0', max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, default='0', max_digits=17, null=True),
        ),
    ]
