# Generated by Django 4.2.6 on 2023-11-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_study_spot_comment_study_spot_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyspot',
            name='comments',
        ),
        migrations.AddField(
            model_name='studyspot',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to='users.comment'),
        ),
    ]
