# Generated by Django 4.2.6 on 2023-11-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_studyspot_latitude_alter_studyspot_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyspot',
            name='latitude',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
        migrations.AlterField(
            model_name='studyspot',
            name='longitude',
            field=models.FloatField(blank=True, default='0.0', null=True),
        ),
    ]
