# Generated by Django 4.2.5 on 2023-11-21 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_studyspot_comments_studyspot_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
    ]
