# Generated by Django 4.2.5 on 2023-11-21 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_studyspot_latitude_alter_studyspot_longitude'),
        ('users', '0015_remove_comment_is_reply'),
    ]

    operations = [
    ]
